% Evaluate reprojection error
N = size(trackedLandmarks, 2);

points_C = R_CW * trackedLandmarks ...
    + repmat(t_CW, [1, size(trackedLandmarks, 2)]);
repr = projectPoints(points_C, K);
repr_err = sum((trackedKeypoints - repr).^2, 'all');

fprintf(strcat(...
'=====================\n', ...
'Reprojection error on tracked landmarks (%d)\n',...
'    Tot: %.3f\n', ...
'    Avg: %.3f\n',...
'=====================\n'), N, repr_err, repr_err / N);